create table if not exists public.events (
  id bigint generated by default as identity primary key,
  "createdAt" timestamptz not null default now(),
  title text not null,
  summary text,
  description text,
  date timestamptz not null,
  "venueName" text,
  "venueAddress" text,
  "venuePostalCode" text,
  "venueCity" text,
  "venueWebsite" text,
  category text,
  image text,
  price integer not null default 0
);

alter table public.events add column if not exists "venuePostalCode" text;
alter table public.events add column if not exists "venueCity" text;
alter table public.events add column if not exists "venueWebsite" text;

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  "createdAt" timestamptz not null default now(),
  name text not null,
  email text not null,
  status text not null default 'Ny',
  "eventTitle" text not null,
  "eventDate" timestamptz not null,
  "eventLocation" text
);

grant select on table public.events to anon;
grant select, insert on table public.registrations to anon;
grant usage, select on all sequences in schema public to anon;

insert into public.events
  (id, title, summary, description, date, "venueName", "venueAddress", "venuePostalCode", "venueCity", "venueWebsite", category, image, price)
values
  (1, 'Lyd mellem husene', 'En intim aften med nye elektroniske navne og visuelle installationer.', 'Oplev tre upcoming artister i et midlertidigt scenerum mellem Godsbanens værksteder. Aftenen kombinerer elektronisk musik, lys og korte artist talks.', '2026-09-12T19:30:00+02:00', 'Godsbanen', 'Skovgaardsgade 3', '8000', 'Aarhus C', 'https://godsbanen.dk/', 'Koncert', 'https://images.unsplash.com/photo-1562423426-934230877f7a?q=80&w=2525&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 120),
  (2, 'Byen efter mørke', 'En talk om lys, tryghed og de steder, vi deler efter solnedgang.', 'Arkitekter, designere og lokale beboere mødes til en samtale om, hvordan lys og byrumsdesign påvirker vores oplevelse af byen efter mørkets frembrud.', '2026-09-18T17:00:00+02:00', 'Dokk1', 'Hack Kampmanns Plads 2', '8000', 'Aarhus C', 'https://dokk1.dk/', 'Talk', 'https://images.unsplash.com/photo-1562535375-d6ce64f58475?q=80&w=2400&auto=format&fit=crop&ixlib=rb-4.1.0', 0),
  (3, 'Tryk din egen plakat', 'Workshop i analogt tryk med former, farver og typografi.', 'En praktisk workshop for begyndere. Du udvikler et enkelt motiv og trykker din egen A3-plakat. Materialer er inkluderet, og du behøver ingen erfaring.', '2026-09-26T10:00:00+02:00', 'Institut for X', 'Skovgaardsgade 3F', '8000', 'Aarhus C', 'https://institutforx.dk/', 'Workshop', 'https://images.unsplash.com/photo-1777751006387-558bdf78a02e?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 175),
  (4, 'Langbord og lokale råvarer', 'Fællesspisning med sæsonens grønt og historier fra producenterne.', 'Vi dækker langbord i gårdrummet og serverer en enkel menu baseret på lokale råvarer. Undervejs fortæller producenterne om råvarerne og arbejdet bag.', '2026-10-02T18:00:00+02:00', 'Folkestedet', 'Carl Blochs Gade 28', '8000', 'Aarhus C', 'https://aarhus.dk/folkestedet/om-folkestedet', 'Fællesskab', 'https://plus.unsplash.com/premium_photo-1692200697697-52442fa20580?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 95),
  (5, 'Nye stemmer på scenen', 'Poetry slam, oplæsning og åbent mikrofonformat for nye skribenter.', 'En scene for korte tekster, spoken word og nye idéer. Aftenen begynder med inviterede oplæsere og slutter med åben mikrofon.', '2026-10-08T19:00:00+02:00', 'Lynfabrikken', 'Vestergade 49B', '8000', 'Aarhus C', null, 'Scene', 'https://images.unsplash.com/photo-1561981898-9c83401e4cfd?q=80&w=3080&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 60),
  (6, 'Tegn byen sammen', 'En rolig søndag med skitsebog, kaffe og fælles byrumsstudier.', 'Vi mødes ved Dokk1 og går en kort rute gennem midtbyen, mens vi tegner undervejs. Til sidst samler vi skitserne over kaffe og deler teknikker og observationer.', '2026-10-18T11:00:00+02:00', 'Dokk1', 'Hack Kampmanns Plads 2', '8000', 'Aarhus C', 'https://dokk1.dk/', 'Workshop', 'https://images.unsplash.com/photo-1559070169-a3077159ee16?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 40),
  (7, 'Arkitekturvandring på Aarhus Ø', 'En guidet tur gennem bydelens markante bygninger og nye byrum.', 'Kom tæt på arkitekturen omkring havnen, og hør fortællingerne om materialer, fællesskab og livet mellem bygningerne.', '2026-10-24T13:00:00+02:00', 'Aarhus Ø', 'Bernhardt Jensens Boulevard 175', '8000', 'Aarhus C', null, 'Byvandring', 'https://images.unsplash.com/photo-1532370778713-1400f3d62094?q=80&w=2400&auto=format&fit=crop&ixlib=rb-4.1.0', 75),
  (8, 'Keramik efter fyraften', 'En aften med ler, enkle teknikker og plads til at arbejde med hænderne.', 'Du lærer at forme en lille kop eller skål i hånden. Underviseren hjælper undervejs, og dit arbejde bliver glaseret og brændt efter workshoppen.', '2026-11-04T17:30:00+01:00', 'Godsbanen', 'Skovgaardsgade 3', '8000', 'Aarhus C', 'https://godsbanen.dk/', 'Workshop', 'https://images.unsplash.com/photo-1781389005078-d9e413d89c94?q=80&w=2400&auto=format&fit=crop&ixlib=rb-4.1.0', 220),
  (9, 'Søndagsjazz ved åen', 'En eftermiddag med levende jazz, varme drikke og udsigt til byen.', 'En lokal kvartet spiller to korte sæt med både klassikere og nye kompositioner. Arrangementet foregår udendørs, hvis vejret tillader det.', '2026-11-15T14:00:00+01:00', 'Åboulevarden', 'Åboulevarden 55', '8000', 'Aarhus C', null, 'Koncert', 'https://images.unsplash.com/photo-1569660437240-b27b957bf210?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 85)
on conflict (id) do update set
  title = excluded.title,
  summary = excluded.summary,
  description = excluded.description,
  date = excluded.date,
  "venueName" = excluded."venueName",
  "venueAddress" = excluded."venueAddress",
  "venuePostalCode" = excluded."venuePostalCode",
  "venueCity" = excluded."venueCity",
  "venueWebsite" = excluded."venueWebsite",
  category = excluded.category,
  image = excluded.image,
  price = excluded.price;

insert into public.registrations
  (id, name, email, status, "eventTitle", "eventDate", "eventLocation")
values
  (1, 'Alma Jensen', 'alma@example.com', 'Bekræftet', 'Lyd mellem husene', '2026-09-12T19:30:00+02:00', 'Godsbanen'),
  (2, 'Noah Larsen', 'noah@example.com', 'Ny', 'Tryk din egen plakat', '2026-09-26T10:00:00+02:00', 'Institut for X')
on conflict (id) do update set
  name = excluded.name,
  email = excluded.email,
  status = excluded.status,
  "eventTitle" = excluded."eventTitle",
  "eventDate" = excluded."eventDate",
  "eventLocation" = excluded."eventLocation";

select setval(pg_get_serial_sequence('public.events', 'id'), coalesce((select max(id) from public.events), 1));
select setval(pg_get_serial_sequence('public.registrations', 'id'), coalesce((select max(id) from public.registrations), 1));
